# Generated by Django 5.1.2 on 2024-12-05 19:46

import abc_back.reviews.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_product_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликован')),
                ('image', models.ImageField(upload_to=abc_back.reviews.models.favorite_review_image_upload_to, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_reviews', related_query_name='favorite_review', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Статичные отзыв',
                'verbose_name_plural': 'Статичные отзывы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликован')),
                ('rate', models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('comment', models.TextField(verbose_name='Комментарии')),
                ('image', models.ImageField(blank=True, null=True, upload_to=abc_back.reviews.models.favorite_review_image_upload_to, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='products.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликован')),
                ('liked', models.BooleanField(default=False, verbose_name='Лайк')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', related_query_name='like', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', related_query_name='like', to='reviews.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Лайк отзыва',
                'verbose_name_plural': 'Лайки отзывов',
                'unique_together': {('review', 'user')},
            },
        ),
    ]
