# Generated by Django 5.1.2 on 2024-11-30 09:28

import abc_back.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('sub_title', models.TextField(verbose_name='Подзаголовок')),
                ('main_poster', models.FileField(blank=True, null=True, upload_to=abc_back.pages.models.file_upload_to, verbose_name='Постер')),
                ('about_title', models.TextField(verbose_name='Заголовок о нас')),
                ('about_text', models.TextField(verbose_name='Текст о нас')),
                ('about_poster', models.FileField(blank=True, null=True, upload_to=abc_back.pages.models.file_upload_to, verbose_name='Постер о нас')),
                ('work_title', models.TextField(verbose_name='Заголовок работы')),
                ('work_text', models.TextField(verbose_name='Текст работы')),
                ('work_poster', models.FileField(blank=True, null=True, upload_to=abc_back.pages.models.file_upload_to, verbose_name='Постер работы')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
