# Generated by Django 5.1.2 on 2024-11-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('main_poster', models.FileField(upload_to='', verbose_name='Постер')),
                ('text', models.TextField(verbose_name='Текст')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('whatsapp', models.CharField(max_length=255, verbose_name='WhatsApp номер')),
                ('telegram', models.CharField(max_length=255, verbose_name='Telegram номер')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
