# Generated by Django 5.1.2 on 2024-11-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставка'},
        ),
    ]
