# Generated by Django 5.1.2 on 2024-12-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_delivery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_poster', models.FileField(upload_to='', verbose_name='Постер')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('subtext', models.TextField(verbose_name='Подтекст')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('whatsapp', models.CharField(max_length=255, verbose_name='WhatsApp номер')),
                ('telegram', models.CharField(max_length=255, verbose_name='Telegram номер')),
            ],
            options={
                'verbose_name': 'Подарочный сертификат',
                'verbose_name_plural': 'Подарочный сертификат',
            },
        ),
    ]
