# Generated by Django 5.1.2 on 2024-12-03 16:03

import abc_back.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_giftcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='main_poster',
            field=models.FileField(blank=True, null=True, upload_to=abc_back.pages.models.file_upload_to, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='main_poster',
            field=models.FileField(blank=True, null=True, upload_to=abc_back.pages.models.file_upload_to, verbose_name='Постер'),
        ),
    ]
