# Generated by Django 5.1.2 on 2024-12-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_delivery_main_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Основное'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Основное'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Основное'),
        ),
    ]
