# Generated by Django 5.1.2 on 2024-12-08 14:44

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Страна, город')),
                ('about_yourself', models.TextField(verbose_name='Расскажите о себе')),
            ],
            options={
                'verbose_name': 'О клиенте',
                'verbose_name_plural': 'О клиентах',
            },
        ),
        migrations.CreateModel(
            name='GiftCertificateOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('buyer_fio', models.CharField(max_length=255, verbose_name='ФИО покупателя')),
                ('buyer_email', models.EmailField(max_length=255, verbose_name='Почта покупателя')),
                ('addressee_name', models.CharField(max_length=255, verbose_name='Имя получателя')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма сертификата')),
                ('addressee_message', models.TextField(verbose_name='Сообщение получателю')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочтено')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
            ],
            options={
                'verbose_name': 'Подарочный сертификат',
                'verbose_name_plural': 'Подарочные сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('question', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вопрос от клиента',
                'verbose_name_plural': 'Вопросы от клиентов',
            },
        ),
    ]
