services:
  db-dev:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=${POSTGRES_DB:?}
    ports:
      - "5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/

  redis-dev:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    depends_on:
      - db-dev

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: abc-back-dev:latest
    env_file:
      - ..env
    ports:
      - ${APP_SERVER_HOST_PORT:?}:8000
    volumes:
      - ${APP_SERVER_HOST_STATIC_PATH:?}:/app/static
      - ${APP_SERVER_HOST_MEDIA_PATH:?}:/app/media
    command: >
      bash -c "cd /app
      && ls -la
      && python manage.py migrate
      && python manage.py collectstatic --no-input
      && gunicorn -c conf/gunicorn/config.py"
    depends_on:
      - db-dev
      - redis-dev

  celery:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: abc-back-dev:latest
    volumes:
      - ${APP_SERVER_HOST_STATIC_PATH:?}:/app/static
      - ${APP_SERVER_HOST_MEDIA_PATH:?}:/app/media
    command: bash -c "cd /app && celery -A abc_back worker -l info"
    env_file:
      - ..env
    depends_on:
      - app
      - db-dev
      - redis-dev

  celery-beat:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: abc-back-dev:latest
    volumes:
      - ${APP_SERVER_HOST_STATIC_PATH:?}:/app/static
      - ${APP_SERVER_HOST_MEDIA_PATH:?}:/app/media
    command: bash -c "cd /app
      && celery -A abc_back beat -l error --scheduler abc_back.celery:DatabaseScheduler --pidfile=celeryd.pid"
    env_file:
      - ..env
    depends_on:
      - app
      - db-dev
      - redis-dev

  flower:
    image: mher/flower:0.9.7
    env_file:
      - ..env
    environment:
      - FLOWER_PORT=$FLOWER_PORT
    ports:
      - ${FLOWER_HOST_PORT:?}:${FLOWER_PORT:?}
    depends_on:
      - celery
      - redis-dev

volumes:
  postgres_data_dev:
  redis_data_dev:
