# Generated by Django 5.1.2 on 2024-11-10 09:38

import abc_back.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_collation='case_insensitive', error_messages={'invalid': 'Пожалуйста, введите корректный email.', 'unique': 'Пользователь с таким email адресом уже зарегистрирован.'}, max_length=254, unique=True, validators=[abc_back.validators.validate_email], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=36, validators=[abc_back.validators.NameValidator()], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=36, validators=[abc_back.validators.NameValidator()], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=36, null=True, validators=[abc_back.validators.NameValidator()], verbose_name='Отчество'),
        ),
    ]
