# Generated by Django 5.1.2 on 2024-12-11 04:09

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0006_alter_subproduct_final_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(max_length=255, verbose_name='Дом')),
                ('additional', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнение')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая сумма')),
                ('sale_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скидка')),
                ('amount_with_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма с учетом скидки')),
                ('delivery_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма доставки')),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая сумма')),
                ('status', models.CharField(choices=[('draftЧерновик', 'Draft'), ('newНовый', 'New'), ('confirmedПодтвержден', 'Confirmed'), ('payedОплачен', 'Payed'), ('in_deliveryВ доставке', 'In Delivery'), ('deliveredДоставлен', 'Delivered'), ('canceledОтменен', 'Canceled'), ('returnedВозврат', 'Returned')], default='draftЧерновик', max_length=24, verbose_name='Статус')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сессия')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='order', to='core.city', verbose_name='Город')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('sell_price', models.FloatField(blank=True, null=True, verbose_name='Цена продажи')),
                ('sale_percent', models.PositiveIntegerField(blank=True, null=True, verbose_name='Процент скидки')),
                ('final_price', models.FloatField(blank=True, null=True, verbose_name='Конечная цена')),
                ('total_sum', models.FloatField(blank=True, null=True, verbose_name='Итоговая сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='orders.order', verbose_name='Заказ')),
                ('sub_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', related_query_name='order_item', to='products.subproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
