# Generated by Django 5.1.2 on 2024-11-29 17:23

import abc_back.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_color_color_name_color_hex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=abc_back.products.models.brand_logo_upload_to, verbose_name='Логотип'),
        ),
    ]
