# Generated by Django 5.1.2 on 2024-12-12 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_subproduct_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='posters',
        ),
        migrations.AddField(
            model_name='subproductimage',
            name='sub_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posters', related_query_name='poster', to='products.subproduct', verbose_name='Подтовар'),
            preserve_default=False,
        ),
    ]
