# Generated by Django 5.1.2 on 2024-12-03 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_brand_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(help_text='Короткое название для URL', max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Короткое название для URL', max_length=255, unique=True, verbose_name='Слаг')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('poster', models.FileField(upload_to='', verbose_name='Постер')),
                ('is_active', models.BooleanField(verbose_name='Активность')),
                ('authors', models.ManyToManyField(related_name='Автор', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='Категории', to='blogs.category')),
                ('related_post', models.ManyToManyField(to='blogs.post', verbose_name='Родитель')),
                ('related_product', models.ManyToManyField(related_name='Связанный продукт+', to='products.product')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пост',
            },
        ),
    ]
