# Generated by Django 5.1.2 on 2024-12-04 06:12

import abc_back.blogs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('products', '0004_brand_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Короткое название для URL', max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', related_query_name='post', to='blogs.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to=abc_back.blogs.models.post_file_upload_to, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='post',
            name='related_post',
            field=models.ManyToManyField(blank=True, null=True, to='blogs.post', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='post',
            name='related_product',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', related_query_name='post', to='products.product', verbose_name='Связанный продукт'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Короткое название для URL', max_length=255, unique=True, verbose_name='Слаг'),
        ),
    ]
