# Generated by Django 5.1.2 on 2024-12-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_slug_alter_post_authors_and_more'),
        ('products', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_post',
            field=models.ManyToManyField(blank=True, to='blogs.post', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='post',
            name='related_product',
            field=models.ManyToManyField(blank=True, related_name='posts', related_query_name='post', to='products.product', verbose_name='Связанный продукт'),
        ),
    ]
